### ISSUE TITLE
Lossy conversion from float64 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.

### ISSUE THREAD

**Issue by alessandro-greco** [cyberdoggos/generator#4]
Hello how can i solve this warn?
Lossy conversion from float64 to uint8. Range [0.0, 255.0]. Convert image to uint8 prior to saving to suppress this warning.

**Comment by Weberowsky** [comment]
Same error

**Comment by Im2rnado** [comment]
You can fix it by updating the following code: 

`image = image.astype(np.uint8)`
right before
`imageio.imwrite(image_path, image)`
