### ISSUE TITLE
Remove duplicate

### ISSUE THREAD

**Issue by sysads** [cyberdoggos/generator#7]
Hi my file size is already 3000 / 3000 pixels but when I run script, it generates the images twice, one normal while the other, it appends _large.

How can I stop it from creating the large one? Thanks

**Comment by cyberdoggos** [comment]
Remove or comment out these two lines in the generator.py script:
`image = self.scale_img(image, self.config['image_scale'])`
`self.save_img(f'{name}_large', image)`
